### ISSUE TITLE
Resource creation doesn't comply with the spec

### ISSUE THREAD

**Issue by neomerx** [nilportugues/laravel5-jsonapi-transformer#2]

**Comment by nilopc** [comment]
Please provide examples

**Comment by neomerx** [comment]
http://jsonapi.org/format/#crud-creating-responses-201

compare with you sample output https://github.com/nilportugues/laravel5-jsonapi-transformer (sorry but you don't have markers)

**Comment by nilopc** [comment]
Ooooh right @neomerx, this is a fix that needs to be done for the https://github.com/nilportugues/jsonapi-transformer/blob/master/src/Http/Message/ResourceCreatedResponse.php file, that's another library.

Thanks for spoting this bug!

**Comment by nilopc** [comment]
Will be solved here: https://github.com/nilportugues/jsonapi-transformer/issues/36

**Comment by neomerx** [comment]
@nilopc And as a 'thank you' for help you unstarred my version. Nice...
