### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by Remo** [nilportugues/laravel5-jsonapi-transformer#6]
I'm trying to get this package working but so far I only get a blank response from `JsonApiSerializer->serialize`. I believe my mappings should be okay, but I'll start debugging this.

It would be great if there was a better error handling and not just a blank return value though. Would certainly make it easier and more fun for those who haven't worked with this package before.

**Comment by Remo** [comment]
once I started debugging I saw the problem, looks like there's an endless loop, not sure why it happens yet:
```
[Mon Sep 07 11:37:52 2015] PHP 119. NilPortugues\Serializer\Serializer->serializeData() /home/remo/jsonapi1/vendor\nilportugues/serializer/src/Serializer.php:469
[Mon Sep 07 11:37:52 2015] PHP 120. NilPortugues\Serializer\DeepCopySerializer->serializeObject() /home/remo/jsonapi1/vendor/nilportugues/serializer/src\Serializer.php:146
[Mon Sep 07 11:37:52 2015] PHP 121. NilPortugues\Serializer\Serializer->serializeInternalClass() /home/remo/jsonapi1/vendor/nilportugues/serializer/src\DeepCopySerializer.php:34
```

**Comment by nilopc** [comment]
Could you provide an example? I'll look into it...

**Comment by nilopc** [comment]
Seems to be failing because it cannot retrieve class properties from internal class... so question is, what's the internal class being used? If it's a special case, I should write its own serializer.

**Comment by Remo** [comment]
I'm using the current laravel version and a super simple class:
```php
namespace Ortic\Models;
class Post extends Model {
}
```

and in my controller:
```php
        $posts = $this->post->all();
        //$posts = $this->post->find(1, ['id']);
        $transformer = $this->serializer->getTransformer();
        $transformer->setSelfUrl(route('posts.index', []));

        $response =  $this->response($this->serializer->serialize($posts));
        return $response;
```

and my config:
```php
<?php
return [
    [
        'class' => 'OrticDb\Models\Post',
        'alias' => '',
        'aliased_properties' => [
        ],
        'hide_properties' => [
        ],
        'id_properties' => [
            'id',
        ],
        'urls' => [
            'self' => 'posts.index',
        ],
    ],
];
```

**Comment by nilopc** [comment]
Laravel Models out of the box use __get(),  meaning properties are magic. I see the problem. 

Should code a special case for the` Illuminate\Database\Eloquent\Model` class, indeed.

I'll treat this as a bug.

**Comment by nilopc** [comment]
Alright I've done some small testing and if nothing goes wrong this fix should up and ready today/tomorrow :+1:

**Comment by nilopc** [comment]
If you can't wait, for now try editing the library's code file:
 `/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApiSerializer/JsonApiSerializer.php`

and replace it for this: https://gist.github.com/nilopc/45a473b2719016c4b22d

Something along the lines should do.... Could not run it (not home)!

**Comment by nilopc** [comment]
@Remo you'll love this: https://github.com/nilportugues/laravel5-jsonapi-transformer/releases/tag/1.2.0 

Thanks once again :) :+1:

**Comment by Remo** [comment]
You're fast, awesome! I'll continue my tests, thanks!

**Comment by nilopc** [comment]
@Remo let me know how it goes :)
